FROM python:3.8
WORKDIR /app
ADD . /app

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6 -y


RUN useradd appuser && chown -R appuser /app
RUN mkdir =p /home/appuser
RUN chown -R appuser /home/appuser/
USER appuser
ENV PATH=$PATH:/home/appuser/.local/bin:/app
ENV PYTHONPATH=/app

RUN pip install -r requirements.txt


CMD ["python", "consumers/cleaner.py"]
