FROM python:3.8

WORKDIR /app
ADD . /app

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6 -y

RUN useradd appuser && chown -R appuser /app
RUN mkdir =p /home/appuser
RUN chown -R appuser /home/appuser/
USER appuser

ENV HOST=docker
ENV PATH=$PATH:/home/appuser/.local/bin:/app
ENV PYTHONPATH=/app
ENV FLASK_APP=main.py
ENV FLASK_RUN_HOST=0.0.0.0

RUN pip install -r requirements.txt

EXPOSE 5000
CMD ["flask", "run"]

