version: "3.8"
services:
  rabbit:
    image: rabbitmq:3.8.9-management
    ports:
    - "15672:15672"
    - "5672:5672"

  api:
    build:
      context: .
      dockerfile: DockerFile_API
    volumes:
      - "./resources:/app/resources"
    ports:
      - "5000:5000"

  cleaner:
    build:
      context: .
      dockerfile: DockerFile_Cleaner
    volumes:
      - "./resources:/app/resources"
        
      